CREATE  TABLE IF NOT EXISTS person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(255)       not null,
                       surname  varchar(255)   not null,
                       age  int                not null
);
